--[=[
 d888b  db    db d888888b      .d888b.      db      db    db  .d8b.  
88' Y8b 88    88   `88'        VP  `8D      88      88    88 d8' `8b 
88      88    88    88            odD'      88      88    88 88ooo88 
88  ooo 88    88    88          .88'        88      88    88 88~~~88 
88. ~8~ 88b  d88   .88.        j88.         88booo. 88b  d88 88   88    @uniquadev
 Y888P  ~Y8888P' Y888888P      888888D      Y88888P ~Y8888P' YP   YP  CONVERTER 
]=]

-- Instances: 107 | Scripts: 1 | Modules: 0 | Tags: 0
local G2L = {};

-- StarterGui.Nevox Hub
G2L["1"] = Instance.new("ScreenGui", game:GetService("Players").LocalPlayer:WaitForChild("PlayerGui"));
G2L["1"]["Name"] = [[Nevox Hub]];
G2L["1"]["ZIndexBehavior"] = Enum.ZIndexBehavior.Sibling;
G2L["1"]["ResetOnSpawn"] = false;


-- StarterGui.Nevox Hub.Main
G2L["2"] = Instance.new("Frame", G2L["1"]);
G2L["2"]["BorderSizePixel"] = 0;
G2L["2"]["BackgroundColor3"] = Color3.fromRGB(45, 45, 45);
G2L["2"]["AnchorPoint"] = Vector2.new(0.5, 0.5);
G2L["2"]["Size"] = UDim2.new(0, 700, 0, 400);
G2L["2"]["Position"] = UDim2.new(0.5, 0, 0.5, 0);
G2L["2"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["2"]["Name"] = [[Main]];


-- StarterGui.Nevox Hub.Main.Top Bar
G2L["3"] = Instance.new("Frame", G2L["2"]);
G2L["3"]["BorderSizePixel"] = 0;
G2L["3"]["BackgroundColor3"] = Color3.fromRGB(6, 6, 6);
G2L["3"]["Size"] = UDim2.new(1, 0, 0, 30);
G2L["3"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["3"]["Name"] = [[Top Bar]];


-- StarterGui.Nevox Hub.Main.Top Bar.UICorner
G2L["4"] = Instance.new("UICorner", G2L["3"]);



-- StarterGui.Nevox Hub.Main.Top Bar.Hide
G2L["5"] = Instance.new("Frame", G2L["3"]);
G2L["5"]["BorderSizePixel"] = 0;
G2L["5"]["BackgroundColor3"] = Color3.fromRGB(6, 6, 6);
G2L["5"]["Size"] = UDim2.new(1, 0, 0, 10);
G2L["5"]["Position"] = UDim2.new(0, 0, 1, -10);
G2L["5"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["5"]["Name"] = [[Hide]];


-- StarterGui.Nevox Hub.Main.Top Bar.Title
G2L["6"] = Instance.new("TextLabel", G2L["3"]);
G2L["6"]["BorderSizePixel"] = 0;
G2L["6"]["TextSize"] = 14;
G2L["6"]["TextXAlignment"] = Enum.TextXAlignment.Left;
G2L["6"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
G2L["6"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Regular, Enum.FontStyle.Normal);
G2L["6"]["TextColor3"] = Color3.fromRGB(171, 86, 255);
G2L["6"]["BackgroundTransparency"] = 1;
G2L["6"]["Size"] = UDim2.new(0, 450, 0, 32);
G2L["6"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["6"]["Text"] = [[Asura Ui Lib]];
G2L["6"]["Name"] = [[Title]];
G2L["6"]["Position"] = UDim2.new(0, 20, 0, 0);


-- StarterGui.Nevox Hub.Main.Top Bar.Line
G2L["7"] = Instance.new("Frame", G2L["3"]);
G2L["7"]["BorderSizePixel"] = 0;
G2L["7"]["BackgroundColor3"] = Color3.fromRGB(171, 86, 255);
G2L["7"]["Size"] = UDim2.new(1, 0, 0, 1);
G2L["7"]["Position"] = UDim2.new(0, 0, 0, 30);
G2L["7"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["7"]["Name"] = [[Line]];


-- StarterGui.Nevox Hub.Main.Top Bar.Exitbtn
G2L["8"] = Instance.new("ImageButton", G2L["3"]);
G2L["8"]["Active"] = false;
G2L["8"]["BorderSizePixel"] = 0;
-- [ERROR] cannot convert ImageContent, please report to "https://github.com/uniquadev/GuiToLuaConverter/issues"
G2L["8"]["BackgroundColor3"] = Color3.fromRGB(26, 18, 18);
G2L["8"]["ImageColor3"] = Color3.fromRGB(171, 86, 255);
G2L["8"]["Selectable"] = false;
G2L["8"]["AnchorPoint"] = Vector2.new(1, 0);
G2L["8"]["Image"] = [[rbxassetid://14477845331]];
G2L["8"]["Size"] = UDim2.new(0, 30, 0, 30);
G2L["8"]["BorderColor3"] = Color3.fromRGB(255, 255, 255);
G2L["8"]["Name"] = [[Exitbtn]];
G2L["8"]["Position"] = UDim2.new(1, -6, 0, 0);


-- StarterGui.Nevox Hub.Main.Top Bar.Exitbtn.Close
G2L["9"] = Instance.new("LocalScript", G2L["8"]);
G2L["9"]["Name"] = [[Close]];


-- StarterGui.Nevox Hub.Main.UICorner
G2L["a"] = Instance.new("UICorner", G2L["2"]);



-- StarterGui.Nevox Hub.Main.DropShadowHolder
G2L["b"] = Instance.new("Frame", G2L["2"]);
G2L["b"]["ZIndex"] = 0;
G2L["b"]["BorderSizePixel"] = 0;
G2L["b"]["Size"] = UDim2.new(1, 0, 1, 0);
G2L["b"]["BorderColor3"] = Color3.fromRGB(28, 43, 54);
G2L["b"]["Name"] = [[DropShadowHolder]];
G2L["b"]["BackgroundTransparency"] = 1;


-- StarterGui.Nevox Hub.Main.DropShadowHolder.DropShadow
G2L["c"] = Instance.new("ImageLabel", G2L["b"]);
G2L["c"]["ZIndex"] = 0;
G2L["c"]["BorderSizePixel"] = 0;
G2L["c"]["SliceCenter"] = Rect.new(49, 49, 450, 450);
G2L["c"]["ScaleType"] = Enum.ScaleType.Slice;
G2L["c"]["ImageTransparency"] = 0.5;
-- [ERROR] cannot convert ImageContent, please report to "https://github.com/uniquadev/GuiToLuaConverter/issues"
G2L["c"]["ImageColor3"] = Color3.fromRGB(0, 0, 0);
G2L["c"]["AnchorPoint"] = Vector2.new(0.5, 0.5);
G2L["c"]["Image"] = [[rbxassetid://6014261993]];
G2L["c"]["Size"] = UDim2.new(1, 47, 1, 47);
G2L["c"]["BorderColor3"] = Color3.fromRGB(28, 43, 54);
G2L["c"]["BackgroundTransparency"] = 1;
G2L["c"]["Name"] = [[DropShadow]];
G2L["c"]["Position"] = UDim2.new(0.5, 0, 0.5, 0);


-- StarterGui.Nevox Hub.Main.Navagition
G2L["d"] = Instance.new("Frame", G2L["2"]);
G2L["d"]["BorderSizePixel"] = 0;
G2L["d"]["BackgroundColor3"] = Color3.fromRGB(6, 6, 6);
G2L["d"]["Size"] = UDim2.new(0, 150, 1, -51);
G2L["d"]["Position"] = UDim2.new(0, 10, 0, 41);
G2L["d"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["d"]["Name"] = [[Navagition]];


-- StarterGui.Nevox Hub.Main.Navagition.UICorner
G2L["e"] = Instance.new("UICorner", G2L["d"]);
G2L["e"]["CornerRadius"] = UDim.new(0, 4);


-- StarterGui.Nevox Hub.Main.Navagition.Button Holder
G2L["f"] = Instance.new("ScrollingFrame", G2L["d"]);
G2L["f"]["BorderSizePixel"] = 0;
G2L["f"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
G2L["f"]["Name"] = [[Button Holder]];
G2L["f"]["Selectable"] = false;
G2L["f"]["Size"] = UDim2.new(1, 0, 1, 0);
G2L["f"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["f"]["ScrollBarThickness"] = 0;
G2L["f"]["BackgroundTransparency"] = 1;


-- StarterGui.Nevox Hub.Main.Navagition.Button Holder.UIListLayout
G2L["10"] = Instance.new("UIListLayout", G2L["f"]);
G2L["10"]["HorizontalAlignment"] = Enum.HorizontalAlignment.Center;
G2L["10"]["Padding"] = UDim.new(0, 10);
G2L["10"]["SortOrder"] = Enum.SortOrder.LayoutOrder;


-- StarterGui.Nevox Hub.Main.Navagition.Button Holder.Title
G2L["11"] = Instance.new("TextLabel", G2L["f"]);
G2L["11"]["BorderSizePixel"] = 0;
G2L["11"]["TextSize"] = 14;
G2L["11"]["TextXAlignment"] = Enum.TextXAlignment.Left;
G2L["11"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
G2L["11"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Regular, Enum.FontStyle.Normal);
G2L["11"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
G2L["11"]["BackgroundTransparency"] = 1;
G2L["11"]["Size"] = UDim2.new(1, 0, 0, 24);
G2L["11"]["ClipsDescendants"] = true;
G2L["11"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["11"]["Text"] = [[Scripts]];
G2L["11"]["Name"] = [[Title]];
G2L["11"]["Position"] = UDim2.new(0, 0, 0, 10);


-- StarterGui.Nevox Hub.Main.Navagition.Button Holder.Title.UIPadding
G2L["12"] = Instance.new("UIPadding", G2L["11"]);
G2L["12"]["PaddingTop"] = UDim.new(0, 10);
G2L["12"]["PaddingLeft"] = UDim.new(0, 5);


-- StarterGui.Nevox Hub.Main.Navagition.Button Holder.Active Tab
G2L["13"] = Instance.new("TextLabel", G2L["f"]);
G2L["13"]["BackgroundColor3"] = Color3.fromRGB(11, 11, 11);
G2L["13"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
G2L["13"]["Size"] = UDim2.new(0, 138, 0, 30);
G2L["13"]["ClipsDescendants"] = true;
G2L["13"]["BorderColor3"] = Color3.fromRGB(171, 86, 255);
G2L["13"]["Text"] = [[Main]];
G2L["13"]["Name"] = [[Active Tab]];
G2L["13"]["Position"] = UDim2.new(0, 6, 0, 0);


-- StarterGui.Nevox Hub.Main.Navagition.Button Holder.inactive Tab
G2L["14"] = Instance.new("TextLabel", G2L["f"]);
G2L["14"]["BackgroundColor3"] = Color3.fromRGB(11, 11, 11);
G2L["14"]["TextColor3"] = Color3.fromRGB(89, 89, 89);
G2L["14"]["Size"] = UDim2.new(0, 138, 0, 30);
G2L["14"]["ClipsDescendants"] = true;
G2L["14"]["BorderColor3"] = Color3.fromRGB(171, 86, 255);
G2L["14"]["Text"] = [[HELLOOO]];
G2L["14"]["Name"] = [[inactive Tab]];
G2L["14"]["Position"] = UDim2.new(0, 6, 0, 0);


-- StarterGui.Nevox Hub.Main.ContentContainer
G2L["15"] = Instance.new("Frame", G2L["2"]);
G2L["15"]["BorderSizePixel"] = 0;
G2L["15"]["BackgroundColor3"] = Color3.fromRGB(6, 6, 6);
G2L["15"]["Size"] = UDim2.new(1, -180, 1, -51);
G2L["15"]["Position"] = UDim2.new(0, 170, 0, 41);
G2L["15"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["15"]["Name"] = [[ContentContainer]];


-- StarterGui.Nevox Hub.Main.ContentContainer.UICorner
G2L["16"] = Instance.new("UICorner", G2L["15"]);
G2L["16"]["CornerRadius"] = UDim.new(0, 4);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab
G2L["17"] = Instance.new("ScrollingFrame", G2L["15"]);
G2L["17"]["BorderSizePixel"] = 0;
G2L["17"]["CanvasPosition"] = Vector2.new(0, 140);
G2L["17"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
G2L["17"]["Name"] = [[Home Tab]];
G2L["17"]["Selectable"] = false;
G2L["17"]["Size"] = UDim2.new(1, 0, 1, 0);
G2L["17"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["17"]["ScrollBarThickness"] = 0;
G2L["17"]["BackgroundTransparency"] = 1;


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Tab Name
G2L["18"] = Instance.new("TextLabel", G2L["17"]);
G2L["18"]["BorderSizePixel"] = 0;
G2L["18"]["TextSize"] = 14;
G2L["18"]["TextXAlignment"] = Enum.TextXAlignment.Left;
G2L["18"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
G2L["18"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Regular, Enum.FontStyle.Normal);
G2L["18"]["TextColor3"] = Color3.fromRGB(171, 86, 255);
G2L["18"]["BackgroundTransparency"] = 1;
G2L["18"]["Size"] = UDim2.new(1, 0, 0, 32);
G2L["18"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["18"]["Text"] = [[Main]];
G2L["18"]["Name"] = [[Tab Name]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Tab Name.UIPadding
G2L["19"] = Instance.new("UIPadding", G2L["18"]);
G2L["19"]["PaddingTop"] = UDim.new(0, 5);
G2L["19"]["PaddingLeft"] = UDim.new(0, 10);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.UIListLayout
G2L["1a"] = Instance.new("UIListLayout", G2L["17"]);
G2L["1a"]["HorizontalAlignment"] = Enum.HorizontalAlignment.Center;
G2L["1a"]["Padding"] = UDim.new(0, 8);
G2L["1a"]["SortOrder"] = Enum.SortOrder.LayoutOrder;


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Button
G2L["1b"] = Instance.new("Frame", G2L["17"]);
G2L["1b"]["BorderSizePixel"] = 0;
G2L["1b"]["BackgroundColor3"] = Color3.fromRGB(31, 31, 31);
G2L["1b"]["Size"] = UDim2.new(1, -20, 0, 32);
G2L["1b"]["Position"] = UDim2.new(0, 10, 0, 20);
G2L["1b"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["1b"]["Name"] = [[Button]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Button.UICorner
G2L["1c"] = Instance.new("UICorner", G2L["1b"]);



-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Button.UIStroke
G2L["1d"] = Instance.new("UIStroke", G2L["1b"]);
G2L["1d"]["Color"] = Color3.fromRGB(171, 86, 255);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Button.Title
G2L["1e"] = Instance.new("TextLabel", G2L["1b"]);
G2L["1e"]["BorderSizePixel"] = 0;
G2L["1e"]["TextSize"] = 14;
G2L["1e"]["TextXAlignment"] = Enum.TextXAlignment.Left;
G2L["1e"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
G2L["1e"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Regular, Enum.FontStyle.Normal);
G2L["1e"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
G2L["1e"]["BackgroundTransparency"] = 1;
G2L["1e"]["Size"] = UDim2.new(1, -40, 0, 22);
G2L["1e"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["1e"]["Text"] = [[Button]];
G2L["1e"]["Name"] = [[Title]];
G2L["1e"]["Position"] = UDim2.new(0, 0, 0, 5);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Button.Title.UIPadding
G2L["1f"] = Instance.new("UIPadding", G2L["1e"]);
G2L["1f"]["PaddingLeft"] = UDim.new(0, 5);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Button.Icon
G2L["20"] = Instance.new("ImageLabel", G2L["1b"]);
G2L["20"]["BorderSizePixel"] = 0;
G2L["20"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
-- [ERROR] cannot convert ImageContent, please report to "https://github.com/uniquadev/GuiToLuaConverter/issues"
G2L["20"]["Image"] = [[rbxassetid://14487416479]];
G2L["20"]["Size"] = UDim2.new(0, 32, 0, 32);
G2L["20"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["20"]["Name"] = [[Icon]];
G2L["20"]["Position"] = UDim2.new(1, -38, 0, 0);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Button.UIPadding
G2L["21"] = Instance.new("UIPadding", G2L["1b"]);



-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Warning
G2L["22"] = Instance.new("Frame", G2L["17"]);
G2L["22"]["BorderSizePixel"] = 0;
G2L["22"]["BackgroundColor3"] = Color3.fromRGB(199, 165, 15);
G2L["22"]["Size"] = UDim2.new(1, -20, 0, 26);
G2L["22"]["Position"] = UDim2.new(0, 10, 0, 20);
G2L["22"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["22"]["Name"] = [[Warning]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Warning.UICorner
G2L["23"] = Instance.new("UICorner", G2L["22"]);
G2L["23"]["CornerRadius"] = UDim.new(0, 4);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Warning.UIStroke
G2L["24"] = Instance.new("UIStroke", G2L["22"]);
G2L["24"]["Color"] = Color3.fromRGB(231, 255, 70);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Warning.Title
G2L["25"] = Instance.new("TextLabel", G2L["22"]);
G2L["25"]["BorderSizePixel"] = 0;
G2L["25"]["TextSize"] = 14;
G2L["25"]["TextXAlignment"] = Enum.TextXAlignment.Left;
G2L["25"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
G2L["25"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Regular, Enum.FontStyle.Normal);
G2L["25"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
G2L["25"]["BackgroundTransparency"] = 1;
G2L["25"]["Size"] = UDim2.new(1, 0, 0, 26);
G2L["25"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["25"]["Text"] = [[Warning]];
G2L["25"]["Name"] = [[Title]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Warning.Title.UIPadding
G2L["26"] = Instance.new("UIPadding", G2L["25"]);
G2L["26"]["PaddingLeft"] = UDim.new(0, 5);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Warning.UIPadding
G2L["27"] = Instance.new("UIPadding", G2L["22"]);
G2L["27"]["PaddingTop"] = UDim.new(0, 2);
G2L["27"]["PaddingLeft"] = UDim.new(0, 30);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Warning.Logo
G2L["28"] = Instance.new("ImageLabel", G2L["22"]);
G2L["28"]["BorderSizePixel"] = 0;
G2L["28"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
-- [ERROR] cannot convert ImageContent, please report to "https://github.com/uniquadev/GuiToLuaConverter/issues"
G2L["28"]["Image"] = [[rbxassetid://14487897769]];
G2L["28"]["Size"] = UDim2.new(0, 26, 0, 26);
G2L["28"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["28"]["Name"] = [[Logo]];
G2L["28"]["Position"] = UDim2.new(0, -25, 0, -2);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Info
G2L["29"] = Instance.new("Frame", G2L["17"]);
G2L["29"]["BorderSizePixel"] = 0;
G2L["29"]["BackgroundColor3"] = Color3.fromRGB(49, 164, 166);
G2L["29"]["Size"] = UDim2.new(1, -20, 0, 26);
G2L["29"]["Position"] = UDim2.new(0, 10, 0, 20);
G2L["29"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["29"]["Name"] = [[Info]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Info.UICorner
G2L["2a"] = Instance.new("UICorner", G2L["29"]);
G2L["2a"]["CornerRadius"] = UDim.new(0, 4);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Info.UIStroke
G2L["2b"] = Instance.new("UIStroke", G2L["29"]);
G2L["2b"]["Color"] = Color3.fromRGB(68, 230, 233);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Info.Title
G2L["2c"] = Instance.new("TextLabel", G2L["29"]);
G2L["2c"]["BorderSizePixel"] = 0;
G2L["2c"]["TextSize"] = 14;
G2L["2c"]["TextXAlignment"] = Enum.TextXAlignment.Left;
G2L["2c"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
G2L["2c"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Regular, Enum.FontStyle.Normal);
G2L["2c"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
G2L["2c"]["BackgroundTransparency"] = 1;
G2L["2c"]["Size"] = UDim2.new(1, 0, 0, 26);
G2L["2c"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["2c"]["Text"] = [[Info]];
G2L["2c"]["Name"] = [[Title]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Info.Title.UIPadding
G2L["2d"] = Instance.new("UIPadding", G2L["2c"]);
G2L["2d"]["PaddingLeft"] = UDim.new(0, 5);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Info.UIPadding
G2L["2e"] = Instance.new("UIPadding", G2L["29"]);
G2L["2e"]["PaddingTop"] = UDim.new(0, 2);
G2L["2e"]["PaddingLeft"] = UDim.new(0, 30);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Info.Logo
G2L["2f"] = Instance.new("ImageLabel", G2L["29"]);
G2L["2f"]["BorderSizePixel"] = 0;
G2L["2f"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
-- [ERROR] cannot convert ImageContent, please report to "https://github.com/uniquadev/GuiToLuaConverter/issues"
G2L["2f"]["Image"] = [[rbxassetid://14487941593]];
G2L["2f"]["Size"] = UDim2.new(0, 26, 0, 26);
G2L["2f"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["2f"]["Name"] = [[Logo]];
G2L["2f"]["Position"] = UDim2.new(0, -25, 0, -2);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Label
G2L["30"] = Instance.new("Frame", G2L["17"]);
G2L["30"]["BorderSizePixel"] = 0;
G2L["30"]["BackgroundColor3"] = Color3.fromRGB(6, 6, 6);
G2L["30"]["Size"] = UDim2.new(1, -20, 0, 26);
G2L["30"]["Position"] = UDim2.new(0, 10, 0, 20);
G2L["30"]["BorderColor3"] = Color3.fromRGB(6, 6, 6);
G2L["30"]["Name"] = [[Label]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Label.UICorner
G2L["31"] = Instance.new("UICorner", G2L["30"]);
G2L["31"]["CornerRadius"] = UDim.new(0, 4);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Label.UIStroke
G2L["32"] = Instance.new("UIStroke", G2L["30"]);
G2L["32"]["Color"] = Color3.fromRGB(121, 121, 121);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Label.Title
G2L["33"] = Instance.new("TextLabel", G2L["30"]);
G2L["33"]["BorderSizePixel"] = 0;
G2L["33"]["TextSize"] = 14;
G2L["33"]["TextXAlignment"] = Enum.TextXAlignment.Left;
G2L["33"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
G2L["33"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Regular, Enum.FontStyle.Normal);
G2L["33"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
G2L["33"]["BackgroundTransparency"] = 1;
G2L["33"]["Size"] = UDim2.new(1, 0, 0, 26);
G2L["33"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["33"]["Name"] = [[Title]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Label.Title.UIPadding
G2L["34"] = Instance.new("UIPadding", G2L["33"]);
G2L["34"]["PaddingLeft"] = UDim.new(0, 5);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Label.UIPadding
G2L["35"] = Instance.new("UIPadding", G2L["30"]);
G2L["35"]["PaddingTop"] = UDim.new(0, 2);
G2L["35"]["PaddingLeft"] = UDim.new(0, 30);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Label.Logo
G2L["36"] = Instance.new("ImageLabel", G2L["30"]);
G2L["36"]["BorderSizePixel"] = 0;
G2L["36"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
-- [ERROR] cannot convert ImageContent, please report to "https://github.com/uniquadev/GuiToLuaConverter/issues"
G2L["36"]["Image"] = [[rbxassetid://14488091307]];
G2L["36"]["Size"] = UDim2.new(0, 26, 0, 26);
G2L["36"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["36"]["Name"] = [[Logo]];
G2L["36"]["Position"] = UDim2.new(0, -25, 0, -2);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Slider
G2L["37"] = Instance.new("Frame", G2L["17"]);
G2L["37"]["BorderSizePixel"] = 0;
G2L["37"]["BackgroundColor3"] = Color3.fromRGB(41, 41, 41);
G2L["37"]["Size"] = UDim2.new(1, -20, 0, 38);
G2L["37"]["Position"] = UDim2.new(0, 10, 0, 20);
G2L["37"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["37"]["Name"] = [[Slider]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Slider.UICorner
G2L["38"] = Instance.new("UICorner", G2L["37"]);
G2L["38"]["CornerRadius"] = UDim.new(0, 4);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Slider.UIStroke
G2L["39"] = Instance.new("UIStroke", G2L["37"]);
G2L["39"]["Color"] = Color3.fromRGB(121, 121, 121);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Slider.Value
G2L["3a"] = Instance.new("TextLabel", G2L["37"]);
G2L["3a"]["BorderSizePixel"] = 0;
G2L["3a"]["TextSize"] = 14;
G2L["3a"]["TextXAlignment"] = Enum.TextXAlignment.Right;
G2L["3a"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
G2L["3a"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Regular, Enum.FontStyle.Normal);
G2L["3a"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
G2L["3a"]["BackgroundTransparency"] = 1;
G2L["3a"]["AnchorPoint"] = Vector2.new(1, 0);
G2L["3a"]["Size"] = UDim2.new(0, 24, 1, -10);
G2L["3a"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["3a"]["Text"] = [[100]];
G2L["3a"]["Name"] = [[Value]];
G2L["3a"]["Position"] = UDim2.new(1, 0, 0, 0);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Slider.Value.UIPadding
G2L["3b"] = Instance.new("UIPadding", G2L["3a"]);
G2L["3b"]["PaddingRight"] = UDim.new(0, 5);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Slider.UIPadding
G2L["3c"] = Instance.new("UIPadding", G2L["37"]);
G2L["3c"]["PaddingTop"] = UDim.new(0, 5);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Slider.Title
G2L["3d"] = Instance.new("TextLabel", G2L["37"]);
G2L["3d"]["BorderSizePixel"] = 0;
G2L["3d"]["TextSize"] = 14;
G2L["3d"]["TextXAlignment"] = Enum.TextXAlignment.Left;
G2L["3d"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
G2L["3d"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Regular, Enum.FontStyle.Normal);
G2L["3d"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
G2L["3d"]["BackgroundTransparency"] = 1;
G2L["3d"]["Size"] = UDim2.new(1, -44, 1, -22);
G2L["3d"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["3d"]["Text"] = [[Slider]];
G2L["3d"]["Name"] = [[Title]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Slider.Title.UIPadding
G2L["3e"] = Instance.new("UIPadding", G2L["3d"]);
G2L["3e"]["PaddingLeft"] = UDim.new(0, 5);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Slider.SliderBack
G2L["3f"] = Instance.new("Frame", G2L["37"]);
G2L["3f"]["BorderSizePixel"] = 0;
G2L["3f"]["BackgroundColor3"] = Color3.fromRGB(18, 18, 18);
G2L["3f"]["AnchorPoint"] = Vector2.new(0, 1);
G2L["3f"]["Size"] = UDim2.new(1, -20, 0, 4);
G2L["3f"]["Position"] = UDim2.new(0, 10, 1, -7);
G2L["3f"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["3f"]["Name"] = [[SliderBack]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Slider.SliderBack.UICorner
G2L["40"] = Instance.new("UICorner", G2L["3f"]);
G2L["40"]["CornerRadius"] = UDim.new(0, 4);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Slider.SliderBack.UIStroke
G2L["41"] = Instance.new("UIStroke", G2L["3f"]);
G2L["41"]["Color"] = Color3.fromRGB(64, 64, 64);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Slider.SliderBack.Draggable
G2L["42"] = Instance.new("Frame", G2L["3f"]);
G2L["42"]["BorderSizePixel"] = 0;
G2L["42"]["BackgroundColor3"] = Color3.fromRGB(35, 63, 223);
G2L["42"]["Size"] = UDim2.new(0.5, 0, 1, 0);
G2L["42"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["42"]["Name"] = [[Draggable]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Slider.SliderBack.Draggable.UICorner
G2L["43"] = Instance.new("UICorner", G2L["42"]);
G2L["43"]["CornerRadius"] = UDim.new(0, 4);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown
G2L["44"] = Instance.new("Frame", G2L["17"]);
G2L["44"]["BorderSizePixel"] = 0;
G2L["44"]["BackgroundColor3"] = Color3.fromRGB(31, 31, 31);
G2L["44"]["ClipsDescendants"] = true;
G2L["44"]["Size"] = UDim2.new(1, -20, 0, 30);
G2L["44"]["Position"] = UDim2.new(0, 10, 0, 20);
G2L["44"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["44"]["Name"] = [[Dropdown]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown.UICorner
G2L["45"] = Instance.new("UICorner", G2L["44"]);
G2L["45"]["CornerRadius"] = UDim.new(0, 4);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown.UIStroke
G2L["46"] = Instance.new("UIStroke", G2L["44"]);
G2L["46"]["Color"] = Color3.fromRGB(121, 121, 121);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown.Title
G2L["47"] = Instance.new("TextLabel", G2L["44"]);
G2L["47"]["BorderSizePixel"] = 0;
G2L["47"]["TextSize"] = 14;
G2L["47"]["TextXAlignment"] = Enum.TextXAlignment.Left;
G2L["47"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
G2L["47"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Regular, Enum.FontStyle.Normal);
G2L["47"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
G2L["47"]["BackgroundTransparency"] = 1;
G2L["47"]["Size"] = UDim2.new(1, -20, 0, 20);
G2L["47"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["47"]["Text"] = [[Dropdown]];
G2L["47"]["Name"] = [[Title]];
G2L["47"]["Position"] = UDim2.new(0, 0, 0, 5);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown.Title.UIPadding
G2L["48"] = Instance.new("UIPadding", G2L["47"]);
G2L["48"]["PaddingLeft"] = UDim.new(0, 5);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown.Icon
G2L["49"] = Instance.new("ImageLabel", G2L["44"]);
G2L["49"]["BorderSizePixel"] = 0;
G2L["49"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
-- [ERROR] cannot convert ImageContent, please report to "https://github.com/uniquadev/GuiToLuaConverter/issues"
G2L["49"]["Image"] = [[rbxassetid://14488859775]];
G2L["49"]["Size"] = UDim2.new(0, 20, 0, 20);
G2L["49"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["49"]["Name"] = [[Icon]];
G2L["49"]["Position"] = UDim2.new(1, -20, 0, 5);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown.UIPadding
G2L["4a"] = Instance.new("UIPadding", G2L["44"]);



-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown.OptionHolder
G2L["4b"] = Instance.new("Frame", G2L["44"]);
G2L["4b"]["Visible"] = false;
G2L["4b"]["BorderSizePixel"] = 0;
G2L["4b"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
G2L["4b"]["Size"] = UDim2.new(1, -20, 1, -24);
G2L["4b"]["Position"] = UDim2.new(0, 10, 0, 26);
G2L["4b"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["4b"]["Name"] = [[OptionHolder]];
G2L["4b"]["BackgroundTransparency"] = 1;


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown.OptionHolder.UIListLayout
G2L["4c"] = Instance.new("UIListLayout", G2L["4b"]);
G2L["4c"]["Padding"] = UDim.new(0, 4);
G2L["4c"]["SortOrder"] = Enum.SortOrder.LayoutOrder;


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown.OptionHolder.Inactive Option
G2L["4d"] = Instance.new("TextLabel", G2L["4b"]);
G2L["4d"]["BorderSizePixel"] = 0;
G2L["4d"]["TextSize"] = 12;
G2L["4d"]["BackgroundColor3"] = Color3.fromRGB(57, 57, 57);
G2L["4d"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Regular, Enum.FontStyle.Normal);
G2L["4d"]["TextColor3"] = Color3.fromRGB(202, 202, 202);
G2L["4d"]["Size"] = UDim2.new(1, 0, 0, 20);
G2L["4d"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["4d"]["Text"] = [[Option]];
G2L["4d"]["Name"] = [[Inactive Option]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown.OptionHolder.Inactive Option.UIStroke
G2L["4e"] = Instance.new("UIStroke", G2L["4d"]);
G2L["4e"]["ApplyStrokeMode"] = Enum.ApplyStrokeMode.Border;
G2L["4e"]["Color"] = Color3.fromRGB(82, 82, 82);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown.OptionHolder.Inactive Option.UICorner
G2L["4f"] = Instance.new("UICorner", G2L["4d"]);
G2L["4f"]["CornerRadius"] = UDim.new(0, 2);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown.OptionHolder.Hover Option
G2L["50"] = Instance.new("TextLabel", G2L["4b"]);
G2L["50"]["BorderSizePixel"] = 0;
G2L["50"]["TextSize"] = 12;
G2L["50"]["BackgroundColor3"] = Color3.fromRGB(57, 57, 57);
G2L["50"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Regular, Enum.FontStyle.Normal);
G2L["50"]["TextColor3"] = Color3.fromRGB(202, 202, 202);
G2L["50"]["Size"] = UDim2.new(1, 0, 0, 20);
G2L["50"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["50"]["Text"] = [[Option]];
G2L["50"]["Name"] = [[Hover Option]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown.OptionHolder.Hover Option.UIStroke
G2L["51"] = Instance.new("UIStroke", G2L["50"]);
G2L["51"]["ApplyStrokeMode"] = Enum.ApplyStrokeMode.Border;
G2L["51"]["Color"] = Color3.fromRGB(255, 255, 255);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown.OptionHolder.Hover Option.UICorner
G2L["52"] = Instance.new("UICorner", G2L["50"]);
G2L["52"]["CornerRadius"] = UDim.new(0, 2);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown.OptionHolder.Active Option
G2L["53"] = Instance.new("TextLabel", G2L["4b"]);
G2L["53"]["BorderSizePixel"] = 0;
G2L["53"]["TextSize"] = 12;
G2L["53"]["BackgroundColor3"] = Color3.fromRGB(86, 86, 86);
G2L["53"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Regular, Enum.FontStyle.Normal);
G2L["53"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
G2L["53"]["Size"] = UDim2.new(1, 0, 0, 20);
G2L["53"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["53"]["Text"] = [[Option]];
G2L["53"]["Name"] = [[Active Option]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown.OptionHolder.Active Option.UIStroke
G2L["54"] = Instance.new("UIStroke", G2L["53"]);
G2L["54"]["ApplyStrokeMode"] = Enum.ApplyStrokeMode.Border;
G2L["54"]["Color"] = Color3.fromRGB(255, 255, 255);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Dropdown.OptionHolder.Active Option.UICorner
G2L["55"] = Instance.new("UICorner", G2L["53"]);
G2L["55"]["CornerRadius"] = UDim.new(0, 2);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle
G2L["56"] = Instance.new("Frame", G2L["17"]);
G2L["56"]["BorderSizePixel"] = 0;
G2L["56"]["BackgroundColor3"] = Color3.fromRGB(31, 31, 31);
G2L["56"]["Size"] = UDim2.new(1, -20, 0, 32);
G2L["56"]["Position"] = UDim2.new(0, 10, 0, 20);
G2L["56"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["56"]["Name"] = [[Toggle]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.UICorner
G2L["57"] = Instance.new("UICorner", G2L["56"]);



-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.UIStroke
G2L["58"] = Instance.new("UIStroke", G2L["56"]);
G2L["58"]["Color"] = Color3.fromRGB(122, 122, 122);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.Title
G2L["59"] = Instance.new("TextLabel", G2L["56"]);
G2L["59"]["BorderSizePixel"] = 0;
G2L["59"]["TextSize"] = 14;
G2L["59"]["TextXAlignment"] = Enum.TextXAlignment.Left;
G2L["59"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
G2L["59"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Regular, Enum.FontStyle.Normal);
G2L["59"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
G2L["59"]["BackgroundTransparency"] = 1;
G2L["59"]["Size"] = UDim2.new(1, -46, 0, 22);
G2L["59"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["59"]["Text"] = [[Toggle]];
G2L["59"]["Name"] = [[Title]];
G2L["59"]["Position"] = UDim2.new(0, 0, 0, 5);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.Title.UIPadding
G2L["5a"] = Instance.new("UIPadding", G2L["59"]);
G2L["5a"]["PaddingLeft"] = UDim.new(0, 5);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.UIPadding
G2L["5b"] = Instance.new("UIPadding", G2L["56"]);



-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.Checkmark Holder
G2L["5c"] = Instance.new("Frame", G2L["56"]);
G2L["5c"]["BorderSizePixel"] = 0;
G2L["5c"]["BackgroundColor3"] = Color3.fromRGB(0, 228, 9);
G2L["5c"]["AnchorPoint"] = Vector2.new(1, 0.5);
G2L["5c"]["Size"] = UDim2.new(0, 24, 0, 24);
G2L["5c"]["Position"] = UDim2.new(1, -7, 0.5, 0);
G2L["5c"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["5c"]["Name"] = [[Checkmark Holder]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.Checkmark Holder.UICorner
G2L["5d"] = Instance.new("UICorner", G2L["5c"]);
G2L["5d"]["CornerRadius"] = UDim.new(0, 2);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.Checkmark Holder.UIStroke
G2L["5e"] = Instance.new("UIStroke", G2L["5c"]);
G2L["5e"]["Color"] = Color3.fromRGB(121, 121, 121);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.Checkmark Holder.Checkmark
G2L["5f"] = Instance.new("ImageLabel", G2L["5c"]);
G2L["5f"]["BorderSizePixel"] = 0;
G2L["5f"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
-- [ERROR] cannot convert ImageContent, please report to "https://github.com/uniquadev/GuiToLuaConverter/issues"
G2L["5f"]["ImageColor3"] = Color3.fromRGB(82, 255, 0);
G2L["5f"]["AnchorPoint"] = Vector2.new(0.5, 0.5);
G2L["5f"]["Image"] = [[rbxassetid://14489384009]];
G2L["5f"]["Size"] = UDim2.new(1, -2, 1, -2);
G2L["5f"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["5f"]["BackgroundTransparency"] = 1;
G2L["5f"]["Name"] = [[Checkmark]];
G2L["5f"]["Position"] = UDim2.new(0.5, 0, 0.5, 0);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle
G2L["60"] = Instance.new("Frame", G2L["17"]);
G2L["60"]["BorderSizePixel"] = 0;
G2L["60"]["BackgroundColor3"] = Color3.fromRGB(31, 31, 31);
G2L["60"]["Size"] = UDim2.new(1, -20, 0, 32);
G2L["60"]["Position"] = UDim2.new(0, 10, 0, 20);
G2L["60"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["60"]["Name"] = [[Toggle]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.UICorner
G2L["61"] = Instance.new("UICorner", G2L["60"]);



-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.UIStroke
G2L["62"] = Instance.new("UIStroke", G2L["60"]);
G2L["62"]["Color"] = Color3.fromRGB(122, 122, 122);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.Title
G2L["63"] = Instance.new("TextLabel", G2L["60"]);
G2L["63"]["BorderSizePixel"] = 0;
G2L["63"]["TextSize"] = 14;
G2L["63"]["TextXAlignment"] = Enum.TextXAlignment.Left;
G2L["63"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
G2L["63"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Regular, Enum.FontStyle.Normal);
G2L["63"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
G2L["63"]["BackgroundTransparency"] = 1;
G2L["63"]["Size"] = UDim2.new(1, -46, 0, 22);
G2L["63"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["63"]["Text"] = [[Toggle]];
G2L["63"]["Name"] = [[Title]];
G2L["63"]["Position"] = UDim2.new(0, 0, 0, 5);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.Title.UIPadding
G2L["64"] = Instance.new("UIPadding", G2L["63"]);
G2L["64"]["PaddingLeft"] = UDim.new(0, 5);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.UIPadding
G2L["65"] = Instance.new("UIPadding", G2L["60"]);



-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.Checkmark Holder
G2L["66"] = Instance.new("Frame", G2L["60"]);
G2L["66"]["BorderSizePixel"] = 0;
G2L["66"]["BackgroundColor3"] = Color3.fromRGB(64, 64, 64);
G2L["66"]["AnchorPoint"] = Vector2.new(1, 0.5);
G2L["66"]["Size"] = UDim2.new(0, 24, 0, 24);
G2L["66"]["Position"] = UDim2.new(1, -7, 0.5, 0);
G2L["66"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["66"]["Name"] = [[Checkmark Holder]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.Checkmark Holder.UICorner
G2L["67"] = Instance.new("UICorner", G2L["66"]);
G2L["67"]["CornerRadius"] = UDim.new(0, 2);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.Checkmark Holder.UIStroke
G2L["68"] = Instance.new("UIStroke", G2L["66"]);
G2L["68"]["Color"] = Color3.fromRGB(121, 121, 121);


-- StarterGui.Nevox Hub.Main.ContentContainer.Home Tab.Toggle.Checkmark Holder.Checkmark
G2L["69"] = Instance.new("ImageLabel", G2L["66"]);
G2L["69"]["BorderSizePixel"] = 0;
G2L["69"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
-- [ERROR] cannot convert ImageContent, please report to "https://github.com/uniquadev/GuiToLuaConverter/issues"
G2L["69"]["AnchorPoint"] = Vector2.new(0.5, 0.5);
G2L["69"]["Image"] = [[rbxassetid://14489384009]];
G2L["69"]["Size"] = UDim2.new(1, -2, 1, -2);
G2L["69"]["Visible"] = false;
G2L["69"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["69"]["BackgroundTransparency"] = 1;
G2L["69"]["Name"] = [[Checkmark]];
G2L["69"]["Position"] = UDim2.new(0.5, 0, 0.5, 0);


-- StarterGui.Nevox Hub.Main.ContentContainer.Fade
G2L["6a"] = Instance.new("Frame", G2L["15"]);
G2L["6a"]["ZIndex"] = 10;
G2L["6a"]["BorderSizePixel"] = 0;
G2L["6a"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
G2L["6a"]["Size"] = UDim2.new(1, 0, 0, 30);
G2L["6a"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
G2L["6a"]["Name"] = [[Fade]];


-- StarterGui.Nevox Hub.Main.ContentContainer.Fade.UIGradient
G2L["6b"] = Instance.new("UIGradient", G2L["6a"]);
G2L["6b"]["Rotation"] = 90;
G2L["6b"]["Transparency"] = NumberSequence.new{NumberSequenceKeypoint.new(0.000, 0),NumberSequenceKeypoint.new(0.341, 0.244),NumberSequenceKeypoint.new(1.000, 1)};
G2L["6b"]["Color"] = ColorSequence.new{ColorSequenceKeypoint.new(0.000, Color3.fromRGB(6, 6, 6)),ColorSequenceKeypoint.new(1.000, Color3.fromRGB(6, 6, 6))};


-- StarterGui.Nevox Hub.Main.Top Bar.Exitbtn.Close
local function C_9()
local script = G2L["9"];
	script.Parent.MouseButton1Click:Connect(function()
		script.Parent.Parent.Parent.Parent.Main.Visible = false
	end)
end;
task.spawn(C_9);

return G2L["1"], require;
